version: '3'

services:
  aplicacion:
    build: .
    ports:
    #local:docker
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    #local:docker
      - "27020:27017"
    volumes:
        - type: bind
          source: ./data
          target: /data/db
